baseurl = "http://jadonbelezos.com/"
relativeURLs = true
title = "jadon's blog"
author = "jadon belezos"
# Shown in the side menu
copyright = "author 2016. jadon belezos"
canonifyurls = true
paginate = 12
theme="blackburn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4


[imaging]
resampleFilter = "box"
# Default JPEG quality setting. Default is 75.
quality = 85
anchor = "smart"
bgColor = "#ffffff"

[imaging.exif]
includeFields = ""
excludeFields = ""
disableDate = false
disableLatLong = true



	
[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = " jadon belezos website"
  brand = "jadon's blog"
  disqus = "mycoder"
  # CSS name for highlight.js
  #highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  
[menu]
#  Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
	[[menu.main]]
	name = "Projects"
	pre = "<i class='fa fa-home fa-fw'></i>"
	weight = 2
	identifier = "project"
	url = "/project/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
	[[menu.main]]
    name = "tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
 
	

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  facebook = "jadon.belezos"
  #googleplus = "*"


  # SNS career oriented
  linkedin = "jadon belezos"

  # Techie
  github = "warlord500"
  stackoverflow = "3458024/5hammer"
  
  #games
  steam = "5hammer"
